### ISSUE TITLE
"changes" relation isn't created

### ISSUE THREAD

**Issue by hash3liZer** [BemiHQ/bemi-django#1]
Hi, i am trying to test this and integrate into a local project with postgres. However, after following all the steps it seems as if the database `changes` isn't created. Instead i get this error: 

```
django.db.utils.ProgrammingError: relation "changes" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "changes
```

**Comment by arjunlol** [comment]
Hi @hash3liZer, thanks for opening this issue!

The changes table can be stored in two ways:

1. Local database: [Documentation here](https://docs.bemi.io/orms/django#local-database)
2. Managed service: For production traffic, you can offload to a [remote database](https://docs.bemi.io/orms/django#remote-database).

For local dev, make sure to run the following Docker command to set up the environment properly:

```
docker run \
  -e DB_HOST=host.docker.internal \
  -e DB_PORT=5432 \
  -e DB_NAME=[YOUR_DATABASE] \
  -e DB_USER=postgres \
  -e DB_PASSWORD=postgres \
  public.ecr.aws/bemi/dev:latest
```
This will store the changes table in your specified Postgres database. Let me know if this resolves the issue!

**Comment by arjunlol** [comment]
Hi @hash3liZer, thanks for opening this issue!

The changes table can be stored in two ways:

Local database: [Documentation here](https://docs.bemi.io/orms/django#local-database)
Managed service: For production traffic, you can offload to a [remote database](https://docs.bemi.io/orms/django#remote-database).
For local dev, make sure to run the following Docker command to set up the environment properly:
```
docker run \
  -e DB_HOST=host.docker.internal \
  -e DB_PORT=5432 \
  -e DB_NAME=[YOUR_DATABASE] \
  -e DB_USER=postgres \
  -e DB_PASSWORD=postgres \
  public.ecr.aws/bemi/dev:latest
```
This will store the changes table in your specified Postgres database. Let me know if this resolves the issue!
